config/routes.rb
Bu::Application.routes.draw do

  resources :groups do
    get :description, on: :member

    resource :posts, only: [:create] do
      get ":renge" => "posts#index", as: "index"
    end

    resource :members, only: [] do #ユーザーが入部する
      put :leave
      put :join
      put :request_to_join
      put :delete_request
    end

    resources :memberships, only: [:index, :destroy] do #管理者が制限付きのグループへの参加を許可する
      member do
        put :confirm
        put :reject
      end
    end

    resources :roles, only: [:index, :show, :update, :destroy] #管理者がユーザーのロールを設定する

    resources :events, only: [:show, :new, :create, :edit, :update, :destroy] do
      member do
        put :cancel
        put :be_active
      end

      resource :attendees, only: [] do
        put :delete
        put :attend
        put :absent
        put :maybe
      end

      resources :comments, only: [:show, :create, :destroy]
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  resource :my, controller: 'my', only: [:show, :edit, :update]
  resources :users, only: [:new, :show]

  get "about" => "welcome#about"
  root :to => 'welcome#index'
end

app/models/group.rb
# coding: utf-8
class Group < ActiveRecord::Base
  class NotGroupOwner < Exception ; end
  class NotGroupManager < Exception ; end
  class NotGroupMember < Exception ; end

  attr_accessible :name, :summary
  attr_protected :owner_user_id

  validates :name, :presence => true, :length => { :maximum => 32 }
  validates :summary, :presence => true, :length => { :maximum => 100 }
  validates :description, :length => { :maximum => 4096 }

  has_many :events, dependent: :destroy, :order => 'started_at desc'
  has_many :posts, dependent: :destroy, :order => 'created_at desc'
  has_many :user_groups, dependent: :destroy
  has_many :users, :through => :user_groups
  has_many :member_requests, dependent: :destroy
  has_many :requesting_users, :source => :user, :through => :member_requests

  def image_src
    image_url.to_s.gsub(/['"<>]/, '')
  end

  def owner?(user)
    owner.id == user.id
  end

  def owner
    User.find(owner_user_id)
  rescue ActiveRecord::RecordNotFound
    User.new(:name => 'testman')
  end

  def owner=(user)
    self.owner_user_id = user.id
  end

  def manager?(user)
    return false unless member?(user)
    return true if owner?(user)
    !!(user and user_groups.find_by_user_id(user.id).role?)
  end

  def member?(user)
    !!(user and users.find_by_id(user.id))
  end

  def requesting_user?(user)
    !!(user and requesting_users.find_by_id(user.id))
  end

  def public?
    permission == 0
  end

  def secret?
    permission == 2
  end

  before_create do |record|
    record.users << record.owner
  end

  before_destroy do |record|
    record.users.size <= 1
  end

  after_update do |record|
    record.member_requests.delete_all if record.public?
  end
end

app/controllers/groups_controller.rb
# coding: utf-8
class GroupsController < ApplicationController
  before_filter :require_current_user, only: [:new, :create, :update, :destroy]

  before_filter :admin_only, only: :index
  before_filter :find_group, only: [:show, :edit, :update, :destroy]
  before_filter :owner_only, only: [:edit, :update, :destroy] #TODO:権限周りはまとめて整理する

  def index
    @groups = Group.all
  end

  def show
    @events  = @group.events.limit(7)
    @members = @group.users.includes(:user_groups).order("user_groups.attendance DESC")
    set_subtitle
  end

  def new
    @group = Group.new
    set_subtitle 'new group'
  end

  def edit
    set_subtitle
  end

  def create(group)
    @group = Group.new(group) do |model|
      model.owner = current_user
    end

    if @group.save
      redirect_to group_url(@group), notice: 'Group was successfully created.'
    else
      render :new
      set_subtitle 'new group'
    end
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to group_url(@group), notice: 'Group was successfully updated.'
    else
      render :edit
      set_subtitle
    end
  end

  def destroy
    if @group.destroy
      redirect_to my_url, notice: 'Group was successfully deleted.'
    else
      redirect_to :back, notice: 'Remove all users.'
    end
  end

  def description #TODO javascriptでやるべき
    redirect_to group_path(show_description: true)
  end

  private

  def set_subtitle(title = nil) #TODO: https://github.com/lwe/page_title_helper
    @subtitle = ": #{title or @group.name}"
  end

  def find_group
    @group = Group.find(params[:id])
  end

  def admin_only #TODO
    user.administrator? or raise(User::NotAdministrator)
  end

  def owner_only #TODO
    only_group_owner(@group)
  end
end

app/views/groups/_events.html.haml
%table.table
  - events.each do |event|
    %tbody
      %tr
        %td
          = link_to image_tag(event.img, :class => :event_icon_small), group_event_path(group_id: group.id, id: event.id)
        %td= month_day(event.started_at)
        %td== (#{hour_min(event.started_at)})
        - unless controller_name == 'groups'
          %td
            - src = event.group.image_src
            - src = 'rails.png' if src.nil? or src.empty?
            =# image_tag src, :width => 16
          %td
            /= link_to to_short(event.group.name, 9, 2), event.group
        %td.bold= link_to to_short(event.title, 16, 2), group_event_path(group_id: group.id, id: event.id)
        %td
          - if event.limit?
            == #{event.attendances.count}/#{event.limit}
          - else
            = event.attendances.count
  
        - if user.nil?
        - elsif event.canceled?
          %td{:colspan => 2}
            .notice_cancel=_ 'This event is canceled!'
        - else
          - atnd = user.atnd(event)
          - if atnd
            %td.atnd=_ atnd.state.capitalize
  
          - if event.ended?
            %td.gray=_'ended'
          - elsif atnd
            %td.update= link_to _(:cancel), delete_group_event_attendees_path(group_id: group.id, event_id: event.id), method: :put, class: 'btn btn-danger'
          - elsif event.group.member?(user)
            %td.update.atnd
              = link_to _(:attend), attend_group_event_attendees_path(group_id: group.id, event_id: event.id), method: :put, class: 'btn btn-primary'
              = link_to _(:absent), absent_group_event_attendees_path(group_id: group.id, event_id: event.id), method: :put, class: 'btn btn-danger'
              = link_to _(:maybe), maybe_group_event_attendees_path(group_id: group.id, event_id: event.id), method: :put, class: 'btn btn-warning'

= javascript_tag '$("img.event_icon_small").MyThumbnail({ thumbWidth:40, thumbHeight:28, backgroundColor:"#fff", imageDivClass:"event_icon_small" });'

app/views/groups/_form.html.haml
= form_for group, html: {class: 'form-horizontal'} do |f|
  -if group.errors.any?
    #error_explanation
      %h2= "#{pluralize(group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - group.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, _(:Name), class: 'control-label'
    .controls
      = f.text_field :name
  .control-group
    = f.label :summary, _(:Summary), class: 'control-label'
    .controls
      = f.text_field :summary, :size => '60'
  .control-group
    = f.label :permission, _(:Permission), class: 'control-label'
    .controls
      = f.select(:permission, [[_('Public'), 0], [_('Must be allowed'), 1], [_('Secret'), 2]])
  .control-group
    = f.label :description, _(:Description), class: 'control-label'
    .controls
      = f.text_area :description, :size => '60x8'
  .control-group
    = f.label :image_url, _(:Image), class: 'control-label'
    .controls
      = f.text_field :image_url, :size => 60
  .control-group
    .controls
      = f.submit 'Save', class: 'btn btn-primary'

app/views/groups/_groups.html.haml
#resize_group_icons
  %table.groups.table
    %thead
      %tr
        %th
        %th=_ 'group name'
        %th=_ 'state'
        - if current_user
          %th=_ 'role'
          %th=_ 'summary'
    - groups.each do |group|
      - next if group.hidden?
      %tbody
        %tr
          %td
            - src = group.image_src
            - src = 'twitter-icon.png' if src.nil? or src.empty?
            = image_tag src, :class => :group_icon_small
          %td.nowrap= link_to to_short(group.name, 16), group_path(group.id)
          - if current_user
            %td.nowrap=_ current_user.status(group)
            %td.nowrap
              - if group.owner?(current_user)
                =_ :owner
              = current_user.role(group)
          %td= to_short group.summary, 50

= javascript_tag '$("#resize_group_icons img").MyThumbnail({ thumbWidth:40, thumbHeight:40, backgroundColor:"#fff", imageDivClass:"group_icon_small" });'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form', group: @group

.bottom_menu
  = link_to 'Back', group_path(@group.id)

app/views/groups/index.html.haml
%h1 Groups

%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th Owner
      %th
      %th
      %th

  - @groups.each do |group|
    %tbody
      %tr
        %td= group.name
        %td= group.description
        %td= group.owner ? group.owner.name : 'none'
        %td= link_to 'Show', group_path(group.id)
        %td= link_to 'Edit', edit_group_path(group.id)
        %td= link_to 'Destroy', group_path(group.id), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1=_'New group'
= render 'form', group: @group

.bottom_menu

app/views/groups/show.html.haml
%p#notice= notice

- is_secret = @group.secret? && !@group.member?(current_user)

%table.table
  %tr
    - if @group.image_url?
      %td.logo
        .logo
          %img.logo{ :src => @group.image_src }
    %td.title
      %h1= @group.name
      %p.summary
        = @group.summary
        - if !is_secret and @group.description? and !params[:show_description]
          &#187;
          = link_to 'もっと詳しく', description_group_path(@group.id), class: 'btn btn-primary'
      .description
        - if !is_secret and params[:show_description]
          %p
            &#171;
            = link_to '説明を閉じる', group_path, class: 'btn btn-primary'

          != html_compiler(@group.description)

      .status.right
        %span.gray
          == #{_ :permission}:
          %b= [_(:Public), _('Must be allowed'), _(:Secret), 2][@group.permission]
          \/
          == #{_ :owner}:
          %b= link_to @group.owner.name, user_path(@group.owner.id)

- is_member = @group.member?(current_user)
- if !is_member and !@group.hidden?
  - if @group.public?
    %p.update= link_to _('join this group'), join_group_members_path(group_id: @group.id), method: :put, class: 'btn btn-primary'
  - elsif @group.requesting_user?(current_user)
    %p.update= link_to _('cancel request'), delete_request_group_members_path(group_id: @group.id), method: :put, class: 'btn btn-danger'
  - else
    %p.update= link_to _('ask to join this group'), request_to_join_group_members_path(group_id: @group.id), method: :put, class: 'btn btn-primary'

- unless is_secret
  .events
    %h2=_ :Events
    = render 'events', { group: @group, events: @events, user: current_user }
  .events_new
    - if is_member
      %p= link_to _('new event'), new_group_event_path(group_id: @group), class: 'btn btn-primary'

  - unless @group.hidden?
    .posts
      %h2=_ :Posts
      %table.table
        - @group.posts.order('created_at desc').limit(3).each do |post|
          %tbody
            %tr
              %td= user_icon post.user, :middle
              %td= link_to year_month_day(post.created_at), index_group_posts_path(group_id: @group.id, renge: post.idx)
              %td
                - if post.subject and !post.subject.empty?
                  %b= to_short post.subject, 20
                  \:
                = to_short post.text, 75
      %p= link_to _(@group.posts.count == 0 ? 'new post' : 'read more'), index_group_posts_path(group_id: @group.id, renge: "all"), class: 'btn btn-primary'

    .users.members
      %h2
        =_ :Users
        == (#{@group.users.count})
      %table.table
        %tr
          %th
          %th ユーザ名
          %th 直近10件参加数
          %th 過去参加数
          %th 役職
          - @events.each do |event|
            %td
              - link = link_to month_day(event.started_at), group_event_path(event.id)
              - if event.ended?
                = link
              - else
                %b= link
        -# @group.users.each do |user|
        - @members.each do |user|
          %tr
            %td
              = user_icon user, :middle
            %td{:class => @group.manager?(user) ? 'bold' : '' }
              = link_to "#{user.name}(#{user.attendance_count(@group)})", user_path(user.id)
            %td
              =# user.user_groups.first.recent_entry_count(10)
              = user.recent_entry_count(@group)
            %td
              = user.group_event_attendance(@group)
            %td
              - if @group.owner?(user)
                =_ :owner
              - else
                = user.role(@group) or _(user.status(@group))
      %p
        = link_to _('listing users'), group_roles_path(group_id: @group.id), class: 'btn btn-primary'
        - if @group.manager?(current_user) and !@group.public?
          - text = "#{_('listing requests')}(#{@group.requesting_users.count})"
          = link_to text, group_memberships_path(group_id: @group.id), class: 'btn btn-primary'

  .bottom_menu
    - if is_member and !@group.owner?(current_user) and !@group.hidden?
      %p.update= link_to _('leave this group'), leave_group_members_path(group_id: @group.id) ,method: :put, class: 'btn btn-warning'
    - if current_user and @group.owner?(current_user)
      %h2=_ 'Admin menu'
      = link_to 'Edit', edit_group_path(@group), class: 'btn btn-primary'
      - if @group.users.count <= 1
        %span
          = link_to 'Destroy', group_path(@group), :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger'
        %script
          document.getElementById("JSOK").style.display = "inline";
          document.getElementById("JSNG").style.display = "none";