config/routes.rb
Bu::Application.routes.draw do

  resources :groups do
    get :description, on: :member

    resource :posts, only: [:create] do
      get ":renge" => "posts#index", as: "index"
    end

    resource :members, only: [] do #ユーザーが入部する
      put :leave
      put :join
      put :request_to_join
      put :delete_request
    end

    resources :memberships, only: [:index, :destroy] do #管理者が制限付きのグループへの参加を許可する
      member do
        put :confirm
        put :reject
      end
    end

    resources :roles, only: [:index, :show, :update, :destroy] #管理者がユーザーのロールを設定する

    resources :events, only: [:show, :new, :create, :edit, :update, :destroy] do
      member do
        put :cancel
        put :be_active
      end

      resource :attendees, only: [] do
        put :delete
        put :attend
        put :absent
        put :maybe
      end

      resources :comments, only: [:show, :create, :destroy]
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  resource :my, controller: 'my', only: [:show, :edit, :update]
  resources :users, only: [:new, :show]

  get "about" => "welcome#about"
  root :to => 'welcome#index'
end

app/models/event.rb
# coding: utf-8
class Event < ActiveRecord::Base
  class NotEventOwner < Exception ; end
  class NotEventManager < Exception ; end

  attr_accessible :title, :limit, :started_at, :ended_at, :group_id, :canceled, :place, :address, :description, :image_url, :ended

  belongs_to :group

  has_many :comments, dependent: :destroy
  has_many :user_events, dependent: :destroy, order: :updated_at
  has_many :users, :through => :user_events

  validates :title,   presence: true,
                      length: { maximum:  32 }
  validates :place,   length: { maximum: 255 }
  validates :address, length: { maximum: 255 }
  validates :limit,   numericality: { greater_than_or_equal_to:    1,
                                      less_than_or_equal_to:    1000 }

  scope :closed, lambda { where(events: { canceled: false }).where("events.ended_at < ?", Time.now) }
  scope :in_recent_times, lambda { order("events.started_at DESC").limit(configatron.recent_entry_coun) }

  def img
    src = image_src
    src = group.image_src if src.empty?
    src = 'rails.png' if src.empty?
    src
  end

  def image_src
    image_url.to_s.gsub(/['"<>]/, '')
  end

  def owner?(user)
    owner.id == user.id
  end

  def owner
    User.find(owner_user_id)
  rescue ActiveRecord::RecordNotFound
    User.new(:name => 'testman')
  end

  def owner=(user)
    self.owner_user_id = user.id
  end

  def manager?(user)
    return true if owner?(user)
    return true if group.manager?(user)
  end

  def attendances
    user_events.where(:state => 'attendance')
  end

  #def absences
  #  user_events.where(:state => 'absence')
  #end

  def waitings
    attendances - attendances.limit(limit)
  end

  def attendees
    attendances.limit(limit).map(&:user)
  end

  def waiting_attendees
    waitings.map(&:user)
  end

  def maybees
    user_events.where(:state => 'maybe').map(&:user)
  end

  def absentees
    user_events.where(:state => 'absence').map(&:user)
  end

  def cancel
    update_attributes!(:canceled => true)
  end

  def be_active
    update_attributes!(:canceled => false)
  end

  def be_ended
    raise if ended?
    transaction do
      update_attributes!(:ended => true)

      waitings.each do |user_event| #なぜこの処理をしているのかよくわかりません
        user_event.state = 'absence'
        user_event.save!
      end

      group.users.each do |user| #なぜこの処理をしているのかよくわかりません
        next if user.user_events.find_by_event_id(self.id)
        user.user_events.create(:event_id => self.id, :state => 'no answer')
      end
    end
  end

  def self.be_ended_all
    t = Time.now
    events = where("started_at < ? and ended_at < ? and ended = ?", t, t, false)
    events.each(&:be_ended)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_current_user, only: [:create, :update, :destroy, :be_active, :cancel]

  rescue_from ActiveRecord::RecordInvalid, :with => -> { redirect_to :back, :notice => 'error' }

  before_filter :find_group
  before_filter :member_only, only: [:new, :edit, :show]
  before_filter :member_only_for_create, only: [:create]
  before_filter :find_event, only: [:show, :update, :destroy]
  before_filter :find_last_event, only: [:new, :edit, :create, :update]
  before_filter :find_event_from_event_id, only: [:cancel, :be_active]
  before_filter :event_manager_only, only: [:update, :destroy, :cancel, :be_active]

  after_filter(only: :show) {
    session[:redirect_path_after_event_show] = group_event_url(group_id: @group.id, id: @event.id)
  }

  # GET /events/1
  def show
    @comment = @event.comments.build
    set_subtitle
  end

  # GET /events/new
  def new
    @event = @group.events.build
    set_subtitle 'new'
  end

  # GET /events/1/edit
  def edit
    @event = @group.events.find(params[:id])
    set_subtitle
  end

  # POST /events
  def create
    @event = @group.events.new(params[:event]) do |model|
      model.owner = current_user
    end

    if @event.save
      redirect_to group_event_url(group_id: @group.to_param, id: @event.to_param), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PUT /events/1
  def update
    if @event.update_attributes(params[:event])
      redirect_to group_event_url(group_id: @group.to_param, id: @event.to_param), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to group_url(@group)
  end

  def cancel
    @event.cancel #TODO 失敗のケースを追加する
    redirect_to group_event_url(id: @event.to_param, group_id: @group.to_param), notice: 'Event was successfully canceled.'
  end

  def be_active
    @event.be_active #TODO 失敗のケースを追加する
    redirect_to group_event_url(id: @event.to_param, group_id: @group.to_param), notice: 'Event is active.'
  end

  private

  def set_subtitle(title = nil)
    @subtitle = ": #{@event.group.name} #{title or @event.title}"
  end

  def find_event
    @event = @group.events.find(params[:id])
  end

  def find_last_event
    @last = @group.events.order("id desc").first
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_only #TODO
    only_group_member(@group) if @group.secret?
  end

  def member_only_for_create #TODO
    only_group_member(@group)
  end

  def event_manager_only #TODO
    only_event_manager(@event)
  end

  def find_event_from_event_id #TODO
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.haml
- is_hidden = group.hidden?
= form_for [group, event], html: {class: 'form-horizontal'} do |f|
  -if event.errors.any?
    #error_explanation
      %h2= "#{pluralize(event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - event.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, value: event.title
      - unless is_hidden
        %span.gray== 過去の入力:#{last.try(:title)}
        %span.gray @todo:クリックで過去の入力を選択
  .control-group
    = f.label :limit, class: 'control-label'
    .controls
      = f.number_field :limit, value: event.limit
      - unless is_hidden
        %span.gray== 過去の入力:#{last.try(:limit)}
  .control-group
    = f.label :place, class: 'control-label'
    .controls
      = f.text_field :place, :value => event.place || last.try(:place)
      - unless is_hidden
        %span.gray== 過去の入力:#{last.try(:place)}
  .control-group
    = f.label :address, class: 'control-label'
    .controls
      = f.text_field :address, :value => event.address || last.try(:address)
      - unless is_hidden
        %span.gray== 過去の入力:#{last.try(:address)}
  .control-group
    = f.label :started_at, class: 'control-label'
    .controls
      = f.datetime_select :started_at, {use_month_numbers: true, minute_step: 10}, {class: 'input-mini'}
  .control-group
    = f.label :ended_at, class: 'control-label'
    .controls
      = f.datetime_select :ended_at, {use_month_numbers: true, minute_step: 10}, {class: 'input-mini'}
  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, :size => '60x8'
  .control-group
    = f.label :image_url, class: 'control-label'
    .controls
      = f.text_field :image_url, value: event.image_url || last.try(:image_url)
      - unless is_hidden
        %span.gray== 過去の入力:#{last.try(:image_url)}
  .control-group
    .controls
      = f.submit 'Save', class: 'btn btn-primary'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form', { event: @event, group: @group, last: @last }

.bottom_menu
  = link_to 'Back', group_event_url(id: @event.id, group_id: @group.id), class: 'btn btn-warning'

app/views/events/new.html.haml
%h3= link_to @group.name, group_url(@group.id)
%h1=_'New event'

= render 'form', { event: @event, group: @group, last: @last}

.bottom_menu
  = link_to 'Back', group_path(@group.id), class: 'btn btn-warning'

app/views/events/show.html.haml
%h1
  - unless @group.hidden?
    = link_to @group.name, group_path(@group.id)
  = @event.title

%p#notice= notice
- if @event.canceled?
  %p#notice_cancel=_ 'This event is canceled!'

- if @event.image_url?
  .logo
    =image_tag @event.image_src

%table.table
  %tbody
    %tr
      %td== #{_ 'event owner'} :
      %td= link_to @event.owner.name, user_path(id: @event.owner.id)
  
    %tr
      %td== #{_ :date} :
      %td
        - s = @event.started_at
        - e = @event.ended_at
        = date_time(s)
        - if e > s
          == ...
          - if s.year == e.year and s.mon == e.mon and s.day == e.day
            = hour_min(e)
          - else
            = date_time(e)
    - if @event.limit?
      %tr
        %td== #{_ :Limit}:
        %td= @event.limit
    - if @event.place?
      %tr
        %td== #{_ :Place}:
        %td= @event.place
    - if @event.address?
      %tr
        %td== #{_ :Address}:
        %td= @event.address

- if @event.description?
  %hr
  .description
    != html_compiler(@event.description)

%hr
.state
  - if @event.ended?
    %p=_ 'This event has ended.'
  %b=_ 'Your state'
  \:
  - if current_user.nil?
    =_ :unknown
    - if @group.public?
      %span.atnd
        %span.attend= link_to _(:attend), attend_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-primary'
    - else
      = link_to 'Please login...', login_path, class: 'btn btn-primary'
  - elsif atnd = current_user.atnd(@event)
    %span.atnd== #{_ atnd.state.capitalize}
    %span= link_to _(:cancel), delete_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-danger'
  - elsif @group.member?(current_user)
    =_ :unknown
    %span.atnd
      %span.attend= link_to _(:attend), attend_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-primary'
      %span.absent= link_to _(:absent), absent_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-danger'
      %span.maybe= link_to _(:maybe), maybe_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-warning'
  - else
    =_ :unknown
    - if @group.public?
      %span.atnd
        %span.attend= link_to _(:attend), attend_group_event_attendees_path(event_id: @event.id), method: :put, class: 'btn btn-primary'
    - else
      You are not a member of
      = link_to @group.name, group_path(@group.id), class: 'btn btn-warning'

%hr

.users.attendees
  %b.group_name
    =_ :Attendees
    - if @event.limit?
      == (#{@event.attendances.count}/#{@event.limit})
    - else
      == (#{@event.attendances.count})
  \:
  - @event.attendees.each do |user|
    = user_name(user)
  - if @event.waiting_attendees.count > 0
    \/
    %b.red=_ :WaitingAttendees
    \:
    %span.gray.waiting_attendees
      - @event.waiting_attendees.each do |user|
        = user_name(user)
.users.absentees
  - absentees = @event.absentees
  - maybees = @event.maybees
  %b.group_name
    =_ :Absentees
    == (#{absentees.size + maybees.size})
  \:
  - absentees.each do |user|
    = user_name(user)
  - if @event.maybees.count > 0
    \/
    %b=_ :Maybe
    \:
    %span.maybees
      - maybees.each do |user|
        = user_name(user)

%h2=_ 'Comments and Logs'
- if current_user and @group.member?(current_user)
  = render 'comments/form', comment: @comment, group: @group, event: @event

%table.comments.table
  %caption
    コメント一覧
  %thead
    %tr
      %th
      %th
        コメント者
      %th
        コメント内容
      %th
        コメント日時
      %th
        コメント詳細
  - @event.comments.order('created_at desc').each do |comment|
    %tbody
      %tr.comment
        %td
          = user_icon comment.user, :middle
        %td.bold
          = link_to comment.user_name, comment.user
        %td
          != comment_html_compiler(comment.text)
        %td
          = date_time(comment.created_at)
        %td
          = link_to 'コメント詳細', group_event_comment_path(group_id: @group.id, event_id: @event.id, id: comment.id), class: 'btn btn-primary'

- if current_user and @event.manager?(current_user)
  .admin_menu
    %h2=_ 'admin menu'
    = link_to _(:Edit), edit_group_event_path(group_id: @group.id, id: @event.id), class: 'btn btn-primary'
    - if @event.canceled?
      = link_to _('Be active'), be_active_group_event_path(group_id: @group.id, id: @event.to_param), method: :put
    - else
      = link_to _('Cancel Event'), cancel_group_event_path(group_id: @group.id, id: @event.to_param), method: :put, class: 'btn btn-warning'
    = link_to _(:Destroy), group_event_path(group_id: @group.id, id: @event.id), :confirm => 'Destroy event: Are you sure?', :method => :delete, class: 'btn btn-danger'

.bottom_menu
  - unless @group.hidden?
    = link_to "部活「#{@group.name}」に戻る", group_path(@group.id), class: 'btn btn-warning'