config/routes.rb
Bu::Application.routes.draw do

  resources :groups do
    get :description, on: :member

    resource :posts, only: [:create] do
      get ":renge" => "posts#index", as: "index"
    end

    resource :members, only: [] do #ユーザーが入部する
      put :leave
      put :join
      put :request_to_join
      put :delete_request
    end

    resources :memberships, only: [:index, :destroy] do #管理者が制限付きのグループへの参加を許可する
      member do
        put :confirm
        put :reject
      end
    end

    resources :roles, only: [:index, :show, :update, :destroy] #管理者がユーザーのロールを設定する

    resources :events, only: [:show, :new, :create, :edit, :update, :destroy] do
      member do
        put :cancel
        put :be_active
      end

      resource :attendees, only: [] do
        put :delete
        put :attend
        put :absent
        put :maybe
      end

      resources :comments, only: [:show, :create, :destroy]
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  resource :my, controller: 'my', only: [:show, :edit, :update]
  resources :users, only: [:new, :show]

  get "about" => "welcome#about"
  root :to => 'welcome#index'
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :find_group, only: [:index, :show, :update, :destroy]
  before_filter :group_member_only, only: [:index, :show]
  before_filter :find_user_group, only: [:update, :destroy]
  before_filter :manager_only, only: [:update, :destroy]
  before_filter :owner_only, only: :destroy

  def index #TODO: members#indexに移動する?
    @events = @group.events
  end

  def show #TODO: members#showに移動する?
    @user = @group.users.find(params[:id])
    @user_group = @user.user_group(@group)

    time = @user_group.created_at
    if oldst = @user.user_events.minimum(:created_at)
      time = oldst if oldst < time
    end
    @events = @group.events.where('created_at >= ?', time)
  end

  def update #TODO: viewが整理されないとリファクタリング辛い
    if @user_group.update_attributes(user_group_params)
      redirect_to group_roles_url(group_id: @group.id), notice: 'Role was successfully updateed.'
    else
      redirect_to group_roles_url(group_id: @group.id)
    end
  end

  def destroy
    @user_group.destroy
    redirect_to group_roles_url(@group.id), notice: 'Remeved member.'
  end

  private
  def group_member_only
     only_group_member(@group) if @group.secret?
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def user_group_params
    { role: params[:user_group].try(:[], :role) }
  end

  def user_group_params
    { role: params[:user_group].try(:[], :role) }
  end

  def find_user_group
    @user_group = UserGroup.find(params[:id])
  end

  def manager_only
    only_group_manager(@group)
  end

  def owner_only
    raise Group::NotGroupOwner if @group.owner?(@user_group.user)
  end
end

app/views/roles/index.html.haml
%h1
  = link_to @group.name, groups_path(@group)
  =_ 'Listing users'

%p#notice= notice

.users
  - is_manager = current_user && @group.manager?(current_user)
  %table.table
    %thead
      %tr
        %th
        %th=_ :name
        %th=_ :state
        =# %th 入部日
        %th 出席
        %th 欠席
        - if is_manager
          %th=_ :mail
        %th=_ :role
        - if is_manager
          %th=_ 'set role'
          %th=_ 'admin menu'
    - @group.users.each do |user|
      %tbody
        %tr
          %td
            %img.user_icon{ :src => user.image, :width => '20' }
          %td{:class => @group.manager?(user) ? 'bold' : '' }
            = link_to user.name, group_role_path(group_id: @group.id, id: user.id)
          %td=_ user.status(@group)
          %td.right= user.attendance_count(@group)
          %td.right= user.absence_count(@group)
          - if is_manager
            %td.center
              = user.mail? ? 'ok' : ''
          %th= user.user_group(@group).role
          - if is_manager
            %td
              =form_for user.user_group(@group), {url: group_role_path(group_id: @group.id, id: user.user_group(@group).id), class: 'form-inline'} do |f|
                %span.field
                  =f.text_field :role, :size => '16', class: 'input-small'
                  %span.actions
                    =f.submit _('Set role'), class: 'btn btn-primary'
            %td
              - unless @group.owner?(user)
                = link_to _(:remove), group_role_path(id: user.user_group(@group), group_id: @group.id), :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger'
.bottom_menu
  = link_to "部活「#{@group.name}」に戻る", group_path(@group.id), class: 'btn btn-warning'
  - if @group.manager?(current_user) and !@group.public?
    - text = "#{_('listing requests')}(#{@group.requesting_users.count})"
    = link_to text, group_memberships_path(group_id: @group.id), class: 'btn btn-primary'

app/views/roles/show.html.haml
%h1
  = link_to @group.name, group_path(@group)
  = @user.name
  =_ "'s ATNDS"

%table.table
  %thead
    %tr
      %th=_ :date
      %th=_ :event
      %th=_ :atnd
  - @events.each do |event|
    %tbody
      %tr
        - atnd = @user.atnd(event)
        %td
          = year_month_day event.started_at
        %td
          %b= link_to to_short(event.title, 12), group_event_path(group_id: @group.id, id: event.id)
        %td.atnd
          - if atnd
            %span.label.label-info=_ atnd.state.capitalize
        %td.gray
          - if event.ended?
            =_'ended'

.bottom_menu
  = link_to "部活「#{@group.name}」に戻る", group_path(@group), class: 'btn btn-warning'
  = link_to "#{_('listing users')}に戻る", group_roles_path, class: 'btn btn-warning'