config/routes.rb
Bu::Application.routes.draw do

  resources :groups do
    get :description, on: :member

    resource :posts, only: [:create] do
      get ":renge" => "posts#index", as: "index"
    end

    resource :members, only: [] do #ユーザーが入部する
      put :leave
      put :join
      put :request_to_join
      put :delete_request
    end

    resources :memberships, only: [:index, :destroy] do #管理者が制限付きのグループへの参加を許可する
      member do
        put :confirm
        put :reject
      end
    end

    resources :roles, only: [:index, :show, :update, :destroy] #管理者がユーザーのロールを設定する

    resources :events, only: [:show, :new, :create, :edit, :update, :destroy] do
      member do
        put :cancel
        put :be_active
      end

      resource :attendees, only: [] do
        put :delete
        put :attend
        put :absent
        put :maybe
      end

      resources :comments, only: [:show, :create, :destroy]
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  resource :my, controller: 'my', only: [:show, :edit, :update]
  resources :users, only: [:new, :show]

  get "about" => "welcome#about"
  root :to => 'welcome#index'
end

app/views/layouts/application.html.haml
!!! XML
!!! 1.1
%html{"xml:lang" => "ja", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title== Bu#{@subtitle}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  %body
    .container-fluid
      .row-fluid
        .span12
          .navbar.navbar-fixed-top.navbar-inverse
            .navbar-inner
              %ul.nav
                - if current_action?('welcome', 'index')
                  %li.active
                    = link_to 'Home', root_path
                - else
                  %li
                    = link_to 'Home', root_path
                - if current_user
                  %li
                    = link_to 'My page', my_path
                - if current_action?('welcome', 'about')
                  %li.active
                    = link_to 'About', about_path
                - else
                  %li
                    = link_to 'About', about_path
              %ul.nav.pull-right
                - if current_user
                  %li
                    = link_to 'Settings', edit_my_path
                  %li
                    = link_to "Sign out(#{current_user.name})", logout_path
                - else
                  %li
                    = link_to 'Sign in with twitter', '/auth/twitter'
      - if current_user and !current_user.mail?
        .input_mail
          %p.bold= link_to 'Please input your mail address', edit_my_path, class: 'btn btn-warning'
      .controller_name
        = yield
      .footer
        %p
          bu:
          = link_to '@dan5ya', 'http://twitter.com/dan5ya'